"""Document and proposal version control models."""

from datetime import datetime
from uuid import uuid4

from sqlalchemy import Column, String, Text, DateTime, ForeignKey, Integer, JSON
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from app.database import Base


class DocumentVersion(Base):
    """Document version for tracking changes."""

    __tablename__ = "document_versions"

    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid4)
    document_id = Column(PGUUID(as_uuid=True), ForeignKey("documents.id"), nullable=False)

    # Version info
    version_number = Column(Integer, nullable=False)
    version_label = Column(String(50), nullable=True)  # e.g., "v1.0", "Draft 2"

    # File info
    file_path = Column(String(500), nullable=False)
    file_size = Column(Integer, default=0)
    file_hash = Column(String(64), nullable=True)  # SHA-256 hash for comparison

    # Content
    extracted_text = Column(Text, nullable=True)

    # Change info
    change_summary = Column(Text, nullable=True)
    changed_by_id = Column(PGUUID(as_uuid=True), ForeignKey("users.id"), nullable=False)

    # Metadata
    metadata = Column(JSON, default={})

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    document = relationship("Document", backref="versions")
    changed_by = relationship("User", backref="document_changes")


class ProposalVersion(Base):
    """Proposal version for tracking changes."""

    __tablename__ = "proposal_versions"

    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid4)
    proposal_id = Column(PGUUID(as_uuid=True), ForeignKey("proposals.id"), nullable=False)

    # Version info
    version_number = Column(Integer, nullable=False)
    version_label = Column(String(50), nullable=True)

    # Content snapshot
    title = Column(String(500), nullable=False)
    content = Column(Text, nullable=True)
    sections = Column(JSON, default=[])
    word_count = Column(Integer, default=0)

    # Scores at time of version
    compliance_score = Column(Integer, nullable=True)

    # Change info
    change_summary = Column(Text, nullable=True)
    changed_by_id = Column(PGUUID(as_uuid=True), ForeignKey("users.id"), nullable=False)

    # Comparison
    diff_from_previous = Column(JSON, default={})

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    proposal = relationship("Proposal", backref="versions")
    changed_by = relationship("User", backref="proposal_changes")


class VersionComparison(Base):
    """Store version comparison results."""

    __tablename__ = "version_comparisons"

    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid4)

    # Versions being compared
    entity_type = Column(String(50), nullable=False)  # 'document' or 'proposal'
    version_a_id = Column(PGUUID(as_uuid=True), nullable=False)
    version_b_id = Column(PGUUID(as_uuid=True), nullable=False)

    # Comparison results
    additions = Column(Integer, default=0)
    deletions = Column(Integer, default=0)
    modifications = Column(Integer, default=0)
    similarity_score = Column(Integer, default=0)  # 0-100

    # Detailed diff
    diff_content = Column(JSON, default={})

    # Generated by
    generated_by_id = Column(PGUUID(as_uuid=True), ForeignKey("users.id"), nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    generated_by = relationship("User", backref="version_comparisons")
