"""Export and reporting service for proposals and projects."""

import io
import json
from typing import Dict, Any, List, Optional
from datetime import datetime
from uuid import UUID
import csv


class ExportService:
    """Service for exporting data in various formats."""

    @staticmethod
    def export_proposal_to_markdown(proposal: Dict[str, Any]) -> str:
        """Export proposal to Markdown format."""
        lines = []

        # Title
        lines.append(f"# {proposal.get('title', 'Untitled Proposal')}")
        lines.append("")

        # Metadata
        lines.append("## Proposal Information")
        lines.append("")
        lines.append(f"- **Status:** {proposal.get('status', 'N/A')}")
        lines.append(f"- **Created:** {proposal.get('created_at', 'N/A')}")
        if proposal.get('word_count'):
            lines.append(f"- **Word Count:** {proposal['word_count']:,}")
        if proposal.get('compliance_score'):
            lines.append(f"- **Compliance Score:** {proposal['compliance_score']}%")
        lines.append("")

        # Content
        if proposal.get('content'):
            lines.append("## Proposal Content")
            lines.append("")
            lines.append(proposal['content'])
            lines.append("")

        # Sections
        if proposal.get('sections'):
            for section in proposal['sections']:
                lines.append(f"## {section.get('title', 'Section')}")
                lines.append("")
                lines.append(section.get('content', ''))
                lines.append("")

        return "\n".join(lines)

    @staticmethod
    def export_proposal_to_html(proposal: Dict[str, Any]) -> str:
        """Export proposal to HTML format."""
        html = []

        html.append("<!DOCTYPE html>")
        html.append("<html lang='en'>")
        html.append("<head>")
        html.append("  <meta charset='UTF-8'>")
        html.append("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>")
        html.append(f"  <title>{proposal.get('title', 'Proposal')}</title>")
        html.append("  <style>")
        html.append("""
    body {
      font-family: 'Georgia', serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      line-height: 1.6;
      color: #333;
    }
    h1 { font-size: 2em; margin-bottom: 0.5em; color: #1a1a1a; }
    h2 { font-size: 1.5em; margin-top: 1.5em; color: #2a2a2a; border-bottom: 1px solid #eee; padding-bottom: 0.3em; }
    h3 { font-size: 1.2em; margin-top: 1em; }
    .meta { background: #f5f5f5; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
    .meta p { margin: 5px 0; font-size: 0.9em; }
    .content { margin-top: 20px; }
    p { margin: 1em 0; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 0.9em; color: #666; }
  """)
        html.append("  </style>")
        html.append("</head>")
        html.append("<body>")

        # Title
        html.append(f"  <h1>{proposal.get('title', 'Untitled Proposal')}</h1>")

        # Metadata
        html.append("  <div class='meta'>")
        html.append(f"    <p><strong>Status:</strong> {proposal.get('status', 'N/A')}</p>")
        html.append(f"    <p><strong>Created:</strong> {proposal.get('created_at', 'N/A')}</p>")
        if proposal.get('word_count'):
            html.append(f"    <p><strong>Word Count:</strong> {proposal['word_count']:,}</p>")
        if proposal.get('compliance_score'):
            html.append(f"    <p><strong>Compliance Score:</strong> {proposal['compliance_score']}%</p>")
        html.append("  </div>")

        # Content
        html.append("  <div class='content'>")
        if proposal.get('content'):
            # Simple paragraph splitting
            paragraphs = proposal['content'].split('\n\n')
            for para in paragraphs:
                if para.startswith('# '):
                    html.append(f"    <h1>{para[2:]}</h1>")
                elif para.startswith('## '):
                    html.append(f"    <h2>{para[3:]}</h2>")
                elif para.startswith('### '):
                    html.append(f"    <h3>{para[4:]}</h3>")
                elif para.strip():
                    html.append(f"    <p>{para}</p>")

        # Sections
        if proposal.get('sections'):
            for section in proposal['sections']:
                html.append(f"    <h2>{section.get('title', 'Section')}</h2>")
                content = section.get('content', '')
                paragraphs = content.split('\n\n')
                for para in paragraphs:
                    if para.strip():
                        html.append(f"    <p>{para}</p>")

        html.append("  </div>")

        # Footer
        html.append("  <div class='footer'>")
        html.append(f"    <p>Generated by Grant Proposal Writer on {datetime.now().strftime('%B %d, %Y')}</p>")
        html.append("  </div>")

        html.append("</body>")
        html.append("</html>")

        return "\n".join(html)

    @staticmethod
    def export_budget_to_csv(budget: Dict[str, Any]) -> str:
        """Export budget to CSV format."""
        output = io.StringIO()
        writer = csv.writer(output)

        # Header
        writer.writerow(['Category', 'Description', 'Amount', 'Justification'])

        # Line items by category
        for category, data in budget.get('by_category', {}).items():
            for item in data.get('items', []):
                writer.writerow([
                    category.title(),
                    item.get('description', ''),
                    f"${item.get('amount', 0):,.2f}",
                    item.get('justification', ''),
                ])

        # Summary
        writer.writerow([])
        writer.writerow(['Summary', '', '', ''])
        writer.writerow(['Total Direct Costs', '', f"${budget.get('total_direct', 0):,.2f}", ''])
        writer.writerow(['Indirect Base', '', f"${budget.get('indirect_base', 0):,.2f}", ''])
        writer.writerow([
            f"Indirect Costs ({budget.get('indirect_rate', 0) * 100:.1f}%)",
            '',
            f"${budget.get('indirect_costs', 0):,.2f}",
            ''
        ])
        writer.writerow(['Total Project Cost', '', f"${budget.get('total', 0):,.2f}", ''])

        return output.getvalue()

    @staticmethod
    def generate_project_report(project: Dict[str, Any], documents: List[Dict], proposals: List[Dict]) -> Dict[str, Any]:
        """Generate comprehensive project report."""
        report = {
            "generated_at": datetime.utcnow().isoformat(),
            "project": {
                "id": str(project.get('id', '')),
                "name": project.get('name', ''),
                "description": project.get('description', ''),
                "status": project.get('status', ''),
                "grant_type": project.get('grant_type', ''),
                "deadline": project.get('deadline'),
                "created_at": project.get('created_at'),
            },
            "statistics": {
                "total_documents": len(documents),
                "total_proposals": len(proposals),
                "documents_by_category": {},
                "documents_by_status": {},
            },
            "documents_summary": [],
            "proposals_summary": [],
            "timeline": [],
            "recommendations": [],
        }

        # Document statistics
        for doc in documents:
            category = doc.get('category', 'other')
            status = doc.get('processing_status', 'unknown')

            if category not in report['statistics']['documents_by_category']:
                report['statistics']['documents_by_category'][category] = 0
            report['statistics']['documents_by_category'][category] += 1

            if status not in report['statistics']['documents_by_status']:
                report['statistics']['documents_by_status'][status] = 0
            report['statistics']['documents_by_status'][status] += 1

            report['documents_summary'].append({
                "name": doc.get('original_filename', ''),
                "category": category,
                "type": doc.get('document_type', ''),
                "status": status,
                "uploaded_at": doc.get('created_at', ''),
            })

        # Proposal statistics
        best_score = None
        for proposal in proposals:
            score = proposal.get('compliance_score')
            if score is not None:
                if best_score is None or score > best_score:
                    best_score = score

            report['proposals_summary'].append({
                "title": proposal.get('title', ''),
                "status": proposal.get('status', ''),
                "word_count": proposal.get('word_count', 0),
                "compliance_score": score,
                "created_at": proposal.get('created_at', ''),
            })

        report['statistics']['best_compliance_score'] = best_score

        # Generate recommendations
        guidelines_count = report['statistics']['documents_by_category'].get('guidelines', 0)
        beneficiary_count = report['statistics']['documents_by_category'].get('beneficiary', 0)

        if guidelines_count == 0:
            report['recommendations'].append({
                "priority": "high",
                "message": "Upload grant guidelines or RFP documents to get started",
            })
        if beneficiary_count == 0:
            report['recommendations'].append({
                "priority": "high",
                "message": "Upload beneficiary information such as organization profile",
            })
        if len(proposals) == 0 and guidelines_count > 0 and beneficiary_count > 0:
            report['recommendations'].append({
                "priority": "medium",
                "message": "You have documents ready - consider generating your first proposal",
            })
        if best_score is not None and best_score < 80:
            report['recommendations'].append({
                "priority": "medium",
                "message": "Review compliance feedback and consider updating your proposal",
            })

        return report

    @staticmethod
    def export_report_to_json(report: Dict[str, Any]) -> str:
        """Export report to JSON format."""
        return json.dumps(report, indent=2, default=str)

    @staticmethod
    def export_documents_list_to_csv(documents: List[Dict]) -> str:
        """Export document list to CSV."""
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow([
            'Filename',
            'Category',
            'Document Type',
            'Processing Status',
            'File Size (bytes)',
            'Uploaded At',
        ])

        for doc in documents:
            writer.writerow([
                doc.get('original_filename', ''),
                doc.get('category', ''),
                doc.get('document_type', ''),
                doc.get('processing_status', ''),
                doc.get('file_size', 0),
                doc.get('created_at', ''),
            ])

        return output.getvalue()
